-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.env("SSH_AUTH_SOCK", os.getenv("XDG_RUNTIME_DIR") .. "/keyring/ssh")

--###############

--## MONITORS ###

--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.monitor({
    output   = "eDP-1",
    mode     = "1920x1080@80",
    position = "0x0",
    scale    = 1,
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use

local terminal = "wezterm"

local fileManager = "dolphin"

local menu = "rofi -show drun"

local switchTheme = "os.getenv(\"HOME\")/.local/bin/wall.sh"

local nightLight = "os.getenv(\"HOME\")/.local/bin/night-light.sh"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:










--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("GTK_IM_MODULE", "fcitx")

hl.env("QT_IM_MODULE", "fcitx")

hl.env("XMODIFIERS", "@im=fcitx")

hl.env("SDL_IM_MODULE", "fcitx")

hl.env("GLFW_IM_MODULE", "fcitx")

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 4,
        border_size = 2,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 5,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 0.95,
        inactive_opacity = 0.7,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 2,
            passes = 3,
            new_optimizations = true,
            xray = true,
            ignore_opacity = true,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/ for more
    },
})
hl.curve("easeOutQuint", {
    type = "bezier",
    points = { { 0.23, 1 }, { 0.32, 1 } },
})
hl.curve("easeInOutCubic", {
    type = "bezier",
    points = { { 0.65, 0.05 }, { 0.36, 1 } },
})
hl.curve("linear", {
    type = "bezier",
    points = { { 0, 0 }, { 1, 1 } },
})
hl.curve("almostLinear", {
    type = "bezier",
    points = { { 0.5, 0.5 }, { 0.75, 1.0 } },
})
hl.curve("quick", {
    type = "bezier",
    points = { { 0.15, 0 }, { 0.1, 1 } },
})
hl.animation({ leaf = "global", enabled = true, speed = 10 })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

-- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

-- workspace = w[tv1], gapsout:0, gapsin:0

-- workspace = f[1], gapsout:0, gapsin:0

-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]

-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]

-- windowrule = bordersize 0, floating:0, onworkspace:f[1]

-- windowrule = rounding 0, floating:0, onworkspace:f[1]

-- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        -- pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true,
        -- You probably want this
    },
})

-- See https://wiki.hypr.land/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
        orientation = "right",
    },
})

-- https://wiki.hypr.land/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_options = "compose:ralt",
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
})

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--##################

--## KEYBINDINGS ###

--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- System binds, see https://wiki.hypr.land/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("wezterm"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "M", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "SPACE", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

-- dwindle

hl.bind(mainMod .. " + " .. "minus", hl.dsp.exec_cmd("wtype \"—\""))

-- Lock

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("swaylock -f -c 000000"))

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "LEFT", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "RIGHT", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "UP", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "DOWN", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- Scroll through existing workspaces with mainMod + scroll

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Toggle Fullscreen

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- Reload Waybar

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("~/dotfiles/waybar/scripts/reload.sh"))

-- Screenshots

hl.bind("Print", hl.dsp.exec_cmd("grim ~/Pictures/Screenshots/Screenshot-$(date +'%Y%m%d-%H%M%S').png"))

hl.bind("SHIFT" .. " + " .. "Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" ~/Pictures/Screenshots/Screenshot-$(date +'%Y%m%d-%H%M%S').png"))

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("grim - | wl-copy"))

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy && wl-paste | swappy -f -"))

-- Record region

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "v", hl.dsp.exec_cmd("~/.config/hypr/scripts/recording_gif.sh"))

-- Record region but don't save to gif

hl.bind(mainMod .. " + " .. "v", hl.dsp.exec_cmd("~/.config/hypr/scripts/recording_mp4.sh"))

-- Clipboard history

hl.bind(mainMod .. " + " .. "z", hl.dsp.exec_cmd("~/.config/hypr/scripts/clipboard-rofi.sh"))

-- Configs

hl.bind(mainMod .. " + " .. "h", hl.dsp.exec_cmd("~/.local/bin/zed ~/dotfiles ~/dotfiles/hypr/.config/hypr/hyprland.conf"))

-- Opacity toggle

--bind = $mainMod, s, movetoworkspacesilent, special

--bind = $mainMod SHIFT, s, togglespecialworkspace

-- Obsidian sync

hl.bind(mainMod .. " + " .. "s", hl.dsp.exec_cmd("~/.config/hypr/scripts/obsidian-sync.sh"))

-- Zulip

-- bind = $mainMod, z, exec, ~/.local/bin/zed ~/Coding/zulip

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true })

-- Requires playerctl

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/wall.sh"))

hl.bind("SUPER" .. " + " .. "N", hl.dsp.exec_cmd(os.getenv("HOME") .. "/.local/bin/night-light.sh toggle"))

-- Keyboard brightness toggle

hl.bind(mainMod .. " + " .. "K", hl.dsp.exec_cmd("~/.config/hypr/scripts/kb-toggle.sh"))

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hypr.land/Configuring/Window-Rules/ for more

-- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule

-- windowrule = float,class:^(kitty)$,title:^(kitty)$

-- Ignore maximize requests from apps. You'll probably like this.

-- TODO: manual review: windowrule2 = "suppress_event maximize", "class:(.*)"

-- Fix some dragging issues with XWayland

-- TODO: manual review: windowrule2 = "no_initial_focus", "class:^$", "title:^$", "xwayland:1", "floating:1", "fullscreen:0", "pinned:0"

--##################

--## PERMISSIONS ###

--##################

-- See https://wiki.hypr.land/Configuring/Permissions/

-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons

-- ecosystem {

--   enforce_permissions = 1

-- }

-- TODO: manual review: permission = "/usr/(bin|local/bin)/grim", "screencopy", "allow"

-- TODO: manual review: permission = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow"

-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar && swaync")
    hl.exec_cmd("ssh-agent -s")
    hl.exec_cmd(" .. os.getenv("HOME") .. "/.config/hypr/scripts/init.sh\"")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secrets,ssh,pkcs11")
    hl.exec_cmd("mako")
    hl.exec_cmd("awww-daemon & disown")
    hl.exec_cmd("fcitx5 -d")
end)
