[opener]
libreoffice = [
    { run = 'lowriter %s', desc = "Open in LibreOffice Writer", orphan = true }
]

pdf = [
    { run = 'firefox-developer-edition %s', orphan = true, desc = "Open in Firefox Dev" }
]

[open]
rules = [
    { url = "*.docx", use = "libreoffice" },
    { url = "*.doc", use = "libreoffice" },
    { url = "*.odt", use = "libreoffice" }, 
]

prepend_rules = [
    { mime = "application/pdf", use = "pdf" }
]
